# Generated by Django 4.2.4 on 2023-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadb',
            name='nome',
            field=models.CharField(choices=[('0', 'Todos'), ('1', 'Biografia'), ('2', 'Economia'), ('3', 'Engenharia'), ('4', 'Escolar'), ('5', 'Ficcao'), ('6', 'Filosofia'), ('7', 'Saude'), ('8', 'Tecnologia')], max_length=50),
        ),
    ]
