# Generated by Django 4.2.4 on 2023-08-31 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0002_alter_livrosdb_options_livrosdb_ano_de_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimosdb',
            options={'verbose_name': 'Empréstimo'},
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='id_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionariosdb'),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosdb'),
        ),
        migrations.AlterField(
            model_name='livrosdb',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='livrosdb',
            name='img_livro',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Funcionariosdb',
        ),
        migrations.DeleteModel(
            name='Usuariosdb',
        ),
    ]
