# Generated by Django 4.2.4 on 2023-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_categoriadb_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadb',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
