# Generated by Django 4.2.4 on 2023-09-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_alter_emprestimosdb_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriadb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='livrosdb',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.categoriadb'),
        ),
    ]
