# Generated by Django 4.2.4 on 2023-09-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_categoriadb_alter_livrosdb_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadb',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
