# Generated by Django 4.2.4 on 2023-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_categoriadb_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrosdb',
            name='img_livro',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
