# Generated by Django 4.2.4 on 2023-09-26 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_livrosdb_img_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 9, 26)),
        ),
    ]
