# Generated by Django 4.2.4 on 2023-10-03 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_livrosdb_img_alter_emprestimosdb_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 10, 3)),
        ),
    ]
