# Generated by Django 4.2.4 on 2023-10-09 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_alter_emprestimosdb_data_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimosdb',
            name='data_retorno_previsto',
            field=models.DateField(default=datetime.date(2023, 10, 16)),
        ),
        migrations.AddField(
            model_name='livrosdb',
            name='qntd_emprestado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livrosdb',
            name='qntd_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 10, 9)),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='situacao',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Atrasado', 'Atrasado'), ('Concluido', 'Concluido')], max_length=30),
        ),
    ]
