# Generated by Django 4.2.4 on 2023-10-12 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_emprestimosdb_data_retorno_previsto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno_previsto',
            field=models.DateField(default=datetime.date(2023, 10, 19)),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 10, 12)),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='situacao',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Atrasado', 'Atrasado'), ('Concluido', 'Concluido')], default='Em andamento', max_length=30),
        ),
    ]
