# Generated by Django 4.2.4 on 2023-10-13 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_alter_emprestimosdb_id_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno_previsto',
            field=models.DateField(default=datetime.date(2023, 10, 20)),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 10, 13)),
        ),
    ]
