# Generated by Django 4.2.4 on 2023-10-26 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_alter_emprestimosdb_data_retorno_previsto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno_previsto',
            field=models.DateField(default=datetime.date(2023, 11, 2)),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
    ]
