# Generated by Django 4.2.4 on 2023-10-29 16:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_alter_emprestimosdb_data_retorno_previsto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno_previsto',
            field=models.DateField(default=datetime.date(2023, 11, 5)),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 10, 29)),
        ),
        migrations.AlterField(
            model_name='livrosdb',
            name='ISBN',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13, 'Certifique-se de digitar um ISBN válido')]),
        ),
        migrations.AlterField(
            model_name='livrosdb',
            name='ano_de_publicacao',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900, 'Certifique-se que o ano de publicação seja maior ou igual a 1900.'), django.core.validators.MaxValueValidator(2023, 'Certifique-se de que o ano de publicação seja uma data válida')]),
        ),
    ]
