# Generated by Django 4.2.4 on 2023-10-30 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_alter_emprestimosdb_data_retorno_previsto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livrosdb',
            old_name='qntd_total',
            new_name='unidades',
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno_previsto',
            field=models.DateField(default=datetime.date(2023, 11, 6)),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 10, 30)),
        ),
    ]
