# Generated by Django 4.2.4 on 2023-10-31 15:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0017_rename_qntd_total_livrosdb_unidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_retorno_previsto',
            field=models.DateField(default=datetime.date(2023, 11, 7)),
        ),
        migrations.AlterField(
            model_name='emprestimosdb',
            name='data_saida',
            field=models.DateField(default=datetime.date(2023, 10, 31)),
        ),
        migrations.AlterField(
            model_name='livrosdb',
            name='unidades',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Certifique-se de que a quantidade de exemplares seja maior ou igual a 1')]),
        ),
    ]
