# Generated by Django 4.2.4 on 2023-11-02 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionariosdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Funcionário',
            },
        ),
        migrations.CreateModel(
            name='Usuariosdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=30)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(default=None, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
            },
        ),
    ]
