# Generated by Django 4.2.4 on 2023-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariosdb_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosdb',
            name='email',
            field=models.EmailField(default=None, max_length=30, null=True),
        ),
    ]
